// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1R3n9UgwK47RhKqLQ6XAFOyw4QayqZw',
    appId: '1:1053633036426:web:f837b70e03ab4bb0c02d73',
    messagingSenderId: '1053633036426',
    projectId: 'spotify01-564cc',
    authDomain: 'spotify01-564cc.firebaseapp.com',
    storageBucket: 'spotify01-564cc.appspot.com',
    measurementId: 'G-B25ZLDJFG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEr7XSY8laUa-EWdt7PILnQEQK50-xnOM',
    appId: '1:1053633036426:android:942fb4ac5da0b735c02d73',
    messagingSenderId: '1053633036426',
    projectId: 'spotify01-564cc',
    storageBucket: 'spotify01-564cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi1T_d9s8fey_NUFCp1aqaasl0y8jAOCo',
    appId: '1:1053633036426:ios:e81b4b10bb5c129cc02d73',
    messagingSenderId: '1053633036426',
    projectId: 'spotify01-564cc',
    storageBucket: 'spotify01-564cc.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi1T_d9s8fey_NUFCp1aqaasl0y8jAOCo',
    appId: '1:1053633036426:ios:e81b4b10bb5c129cc02d73',
    messagingSenderId: '1053633036426',
    projectId: 'spotify01-564cc',
    storageBucket: 'spotify01-564cc.appspot.com',
    iosBundleId: 'com.example.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN1R3n9UgwK47RhKqLQ6XAFOyw4QayqZw',
    appId: '1:1053633036426:web:6e33bb59ef782f9fc02d73',
    messagingSenderId: '1053633036426',
    projectId: 'spotify01-564cc',
    authDomain: 'spotify01-564cc.firebaseapp.com',
    storageBucket: 'spotify01-564cc.appspot.com',
    measurementId: 'G-YSVZXHBMLS',
  );
}
